services:
  nats:
    image: nats:latest
    restart: unless-stopped
    ports:
      - "4222:4222"

  data:
    build:
      context: ./data
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats:4222
    volumes:
      - ./data/bin:/app/bin:ro

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats:4222
