// Package buff provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package buff

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for Phase.
const (
	PhaseBlackPearl Phase = "Black_Pearl"
	PhaseP1         Phase = "P1"
	PhaseP2         Phase = "P2"
	PhaseP3         Phase = "P3"
	PhaseP4         Phase = "P4"
	PhaseRuby       Phase = "Ruby"
	PhaseSapphire   Phase = "Sapphire"
)

// AssetInfo defines model for AssetInfo.
type AssetInfo struct {
	Appid               int      `json:"appid"`
	Assetid             string   `json:"assetid"`
	Classid             string   `json:"classid"`
	Contextid           int      `json:"contextid"`
	GoodsId             int      `json:"goods_id"`
	HasTradableCooldown bool     `json:"has_tradable_cooldown"`
	Id                  string   `json:"id"`
	Info                ItemInfo `json:"info"`
	Instanceid          string   `json:"instanceid"`
	Paintwear           string   `json:"paintwear"`
}

// BaseResponse defines model for BaseResponse.
type BaseResponse struct {
	Code string  `json:"code"`
	Msg  *string `json:"msg"`
}

// BuyOrder defines model for BuyOrder.
type BuyOrder struct {
	AllowTradableCooldown int           `json:"allow_tradable_cooldown"`
	Appid                 int           `json:"appid"`
	CreatedAt             int           `json:"created_at"`
	ExpireTime            *int          `json:"expire_time"`
	Fee                   string        `json:"fee"`
	FrozenAmount          string        `json:"frozen_amount"`
	FrozenNum             int           `json:"frozen_num"`
	Game                  string        `json:"game"`
	GoodsId               int           `json:"goods_id"`
	IconUrl               string        `json:"icon_url"`
	Id                    string        `json:"id"`
	Num                   int           `json:"num"`
	PayExpireTimeout      int           `json:"pay_expire_timeout"`
	PayMethod             int           `json:"pay_method"`
	PayMethodText         string        `json:"pay_method_text"`
	Price                 string        `json:"price"`
	RealNum               int           `json:"real_num"`
	Specific              []interface{} `json:"specific"`
	State                 string        `json:"state"`
	StateText             string        `json:"state_text"`
	TradableCooldown      *int          `json:"tradable_cooldown"`
	UpdatedAt             int           `json:"updated_at"`
	UserId                string        `json:"user_id"`
}

// BuyOrderData defines model for BuyOrderData.
type BuyOrderData struct {
	Items             []BuyOrder          `json:"items"`
	PageNum           int                 `json:"page_num"`
	PageSize          int                 `json:"page_size"`
	ShowPayMethodIcon bool                `json:"show_pay_method_icon"`
	TotalCount        int                 `json:"total_count"`
	TotalPage         int                 `json:"total_page"`
	UserInfos         map[string]UserInfo `json:"user_infos"`
}

// BuyOrderResponse defines model for BuyOrderResponse.
type BuyOrderResponse struct {
	Code string       `json:"code"`
	Data BuyOrderData `json:"data"`
	Msg  *string      `json:"msg"`
}

// GoodsInfo defines model for GoodsInfo.
type GoodsInfo struct {
	Appid          int    `json:"appid"`
	Game           string `json:"game"`
	GoodsId        int    `json:"goods_id"`
	MarketHashName string `json:"market_hash_name"`
	Name           string `json:"name"`
	SellMinPrice   string `json:"sell_min_price"`
	SteamPrice     string `json:"steam_price"`
}

// ItemInfo defines model for ItemInfo.
type ItemInfo struct {
	IconUrl         string                   `json:"icon_url"`
	Keychains       []map[string]interface{} `json:"keychains"`
	OriginalIconUrl string                   `json:"original_icon_url"`
	Paintindex      int                      `json:"paintindex"`
	Paintseed       int                      `json:"paintseed"`
	PhaseData       *PhaseData               `json:"phase_data,omitempty"`
	Stickers        []Sticker                `json:"stickers"`
}

// Phase defines model for Phase.
type Phase string

// PhaseData defines model for PhaseData.
type PhaseData struct {
	Name Phase `json:"name"`
}

// SellOrder defines model for SellOrder.
type SellOrder struct {
	AllowBargain        bool      `json:"allow_bargain"`
	Appid               int       `json:"appid"`
	AssetInfo           AssetInfo `json:"asset_info"`
	Bookmarked          bool      `json:"bookmarked"`
	CanBargain          bool      `json:"can_bargain"`
	CreatedAt           int       `json:"created_at"`
	Fee                 string    `json:"fee"`
	Game                string    `json:"game"`
	GoodsId             int       `json:"goods_id"`
	Id                  string    `json:"id"`
	Income              string    `json:"income"`
	Mode                int       `json:"mode"`
	OrderType           int       `json:"order_type"`
	Price               string    `json:"price"`
	State               int       `json:"state"`
	StateText           string    `json:"state_text"`
	SupportedPayMethods []int     `json:"supported_pay_methods"`
	UpdatedAt           int       `json:"updated_at"`
	UserId              string    `json:"user_id"`
}

// SellOrderData defines model for SellOrderData.
type SellOrderData struct {
	GoodsInfos      map[string]GoodsInfo `json:"goods_infos"`
	HasMarketStores map[string]bool      `json:"has_market_stores"`
	Items           []SellOrder          `json:"items"`
	PageNum         int                  `json:"page_num"`
	PageSize        int                  `json:"page_size"`
	SortBy          string               `json:"sort_by"`
	TotalCount      int                  `json:"total_count"`
	TotalPage       int                  `json:"total_page"`
	UserInfos       map[string]UserInfo  `json:"user_infos"`
}

// SellOrderResponse defines model for SellOrderResponse.
type SellOrderResponse struct {
	Code string        `json:"code"`
	Data SellOrderData `json:"data"`
	Msg  *string       `json:"msg"`
}

// Sticker defines model for Sticker.
type Sticker struct {
	Category string   `json:"category"`
	ImgUrl   string   `json:"img_url"`
	Name     string   `json:"name"`
	Slot     int      `json:"slot"`
	Wear     *float32 `json:"wear,omitempty"`
}

// UserInfo defines model for UserInfo.
type UserInfo struct {
	Avatar       string    `json:"avatar"`
	AvatarSafe   string    `json:"avatar_safe"`
	IsAutoAccept bool      `json:"is_auto_accept"`
	IsPremiumVip bool      `json:"is_premium_vip"`
	Nickname     string    `json:"nickname"`
	SellerLevel  int       `json:"seller_level"`
	ShopId       string    `json:"shop_id"`
	UserId       string    `json:"user_id"`
	VTypes       *[]string `json:"v_types"`
}

// GetApiMarketGoodsBuyOrderParams defines parameters for GetApiMarketGoodsBuyOrder.
type GetApiMarketGoodsBuyOrderParams struct {
	Game       string `form:"game" json:"game"`
	GoodsId    int    `form:"goods_id" json:"goods_id"`
	PageNum    *int   `form:"page_num,omitempty" json:"page_num,omitempty"`
	Underscore *int   `form:"_,omitempty" json:"_,omitempty"`
}

// GetApiMarketGoodsSellOrderParams defines parameters for GetApiMarketGoodsSellOrder.
type GetApiMarketGoodsSellOrderParams struct {
	Game                  string  `form:"game" json:"game"`
	GoodsId               int     `form:"goods_id" json:"goods_id"`
	PageNum               *int    `form:"page_num,omitempty" json:"page_num,omitempty"`
	SortBy                *string `form:"sort_by,omitempty" json:"sort_by,omitempty"`
	Mode                  *string `form:"mode,omitempty" json:"mode,omitempty"`
	AllowTradableCooldown *int    `form:"allow_tradable_cooldown,omitempty" json:"allow_tradable_cooldown,omitempty"`
	Underscore            *int    `form:"_,omitempty" json:"_,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetApiMarketGoodsBuyOrder request
	GetApiMarketGoodsBuyOrder(ctx context.Context, params *GetApiMarketGoodsBuyOrderParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiMarketGoodsSellOrder request
	GetApiMarketGoodsSellOrder(ctx context.Context, params *GetApiMarketGoodsSellOrderParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetApiMarketGoodsBuyOrder(ctx context.Context, params *GetApiMarketGoodsBuyOrderParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiMarketGoodsBuyOrderRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiMarketGoodsSellOrder(ctx context.Context, params *GetApiMarketGoodsSellOrderParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiMarketGoodsSellOrderRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetApiMarketGoodsBuyOrderRequest generates requests for GetApiMarketGoodsBuyOrder
func NewGetApiMarketGoodsBuyOrderRequest(server string, params *GetApiMarketGoodsBuyOrderParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/market/goods/buy_order")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "game", runtime.ParamLocationQuery, params.Game); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "goods_id", runtime.ParamLocationQuery, params.GoodsId); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.PageNum != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page_num", runtime.ParamLocationQuery, *params.PageNum); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Underscore != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "_", runtime.ParamLocationQuery, *params.Underscore); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiMarketGoodsSellOrderRequest generates requests for GetApiMarketGoodsSellOrder
func NewGetApiMarketGoodsSellOrderRequest(server string, params *GetApiMarketGoodsSellOrderParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/market/goods/sell_order")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "game", runtime.ParamLocationQuery, params.Game); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "goods_id", runtime.ParamLocationQuery, params.GoodsId); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.PageNum != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page_num", runtime.ParamLocationQuery, *params.PageNum); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.SortBy != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "sort_by", runtime.ParamLocationQuery, *params.SortBy); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Mode != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "mode", runtime.ParamLocationQuery, *params.Mode); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.AllowTradableCooldown != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "allow_tradable_cooldown", runtime.ParamLocationQuery, *params.AllowTradableCooldown); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Underscore != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "_", runtime.ParamLocationQuery, *params.Underscore); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetApiMarketGoodsBuyOrderWithResponse request
	GetApiMarketGoodsBuyOrderWithResponse(ctx context.Context, params *GetApiMarketGoodsBuyOrderParams, reqEditors ...RequestEditorFn) (*GetApiMarketGoodsBuyOrderResponse, error)

	// GetApiMarketGoodsSellOrderWithResponse request
	GetApiMarketGoodsSellOrderWithResponse(ctx context.Context, params *GetApiMarketGoodsSellOrderParams, reqEditors ...RequestEditorFn) (*GetApiMarketGoodsSellOrderResponse, error)
}

type GetApiMarketGoodsBuyOrderResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BuyOrderResponse
}

// Status returns HTTPResponse.Status
func (r GetApiMarketGoodsBuyOrderResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiMarketGoodsBuyOrderResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiMarketGoodsSellOrderResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SellOrderResponse
}

// Status returns HTTPResponse.Status
func (r GetApiMarketGoodsSellOrderResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiMarketGoodsSellOrderResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetApiMarketGoodsBuyOrderWithResponse request returning *GetApiMarketGoodsBuyOrderResponse
func (c *ClientWithResponses) GetApiMarketGoodsBuyOrderWithResponse(ctx context.Context, params *GetApiMarketGoodsBuyOrderParams, reqEditors ...RequestEditorFn) (*GetApiMarketGoodsBuyOrderResponse, error) {
	rsp, err := c.GetApiMarketGoodsBuyOrder(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiMarketGoodsBuyOrderResponse(rsp)
}

// GetApiMarketGoodsSellOrderWithResponse request returning *GetApiMarketGoodsSellOrderResponse
func (c *ClientWithResponses) GetApiMarketGoodsSellOrderWithResponse(ctx context.Context, params *GetApiMarketGoodsSellOrderParams, reqEditors ...RequestEditorFn) (*GetApiMarketGoodsSellOrderResponse, error) {
	rsp, err := c.GetApiMarketGoodsSellOrder(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiMarketGoodsSellOrderResponse(rsp)
}

// ParseGetApiMarketGoodsBuyOrderResponse parses an HTTP response from a GetApiMarketGoodsBuyOrderWithResponse call
func ParseGetApiMarketGoodsBuyOrderResponse(rsp *http.Response) (*GetApiMarketGoodsBuyOrderResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiMarketGoodsBuyOrderResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BuyOrderResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiMarketGoodsSellOrderResponse parses an HTTP response from a GetApiMarketGoodsSellOrderWithResponse call
func ParseGetApiMarketGoodsSellOrderResponse(rsp *http.Response) (*GetApiMarketGoodsSellOrderResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiMarketGoodsSellOrderResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SellOrderResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
