// Package buffqueue provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package buffqueue

// Item defines model for Item.
type Item struct {
	// Buff163GoodsId Primary ID for Buff163.
	Buff163GoodsId int `json:"buff163_goods_id"`

	// Buff163PaintseedGroupIds Pattern group IDs, such as Blue Gems for Case Hardened items.
	Buff163PaintseedGroupIds *map[string]int `json:"buff163_paintseed_group_ids,omitempty"`

	// Buff163PatchId Specialized ID for agent patches.
	Buff163PatchId *int `json:"buff163_patch_id,omitempty"`

	// Buff163PhaseIds Maps specific Doppler/Gamma Doppler phases to Buff163 IDs.
	Buff163PhaseIds *PhaseIds `json:"buff163_phase_ids,omitempty"`

	// Buff163StickerId Specialized ID for stickers.
	Buff163StickerId *int `json:"buff163_sticker_id,omitempty"`

	// BuffmarketGoodsId Primary ID for BuffMarket.
	BuffmarketGoodsId int `json:"buffmarket_goods_id"`

	// PatternGroups Arrays of paint seeds for specific Fade percentages or patterns.
	PatternGroups *PatternGroups `json:"pattern_groups,omitempty"`

	// YoupinId Primary ID for Youpin.
	YoupinId int `json:"youpin_id"`
}

// ItemMapping Buff mapping object
type ItemMapping struct {
	Items map[string]Item `json:"items"`
}

// PatternGroups Arrays of paint seeds for specific Fade percentages or patterns.
type PatternGroups map[string][]int

// PhaseIds Maps specific Doppler/Gamma Doppler phases to Buff163 IDs.
type PhaseIds struct {
	BlackPearl *int `json:"Black Pearl,omitempty"`
	Emerald    *int `json:"Emerald,omitempty"`
	Phase1     *int `json:"Phase 1,omitempty"`
	Phase2     *int `json:"Phase 2,omitempty"`
	Phase3     *int `json:"Phase 3,omitempty"`
	Phase4     *int `json:"Phase 4,omitempty"`
	Ruby       *int `json:"Ruby,omitempty"`
	Sapphire   *int `json:"Sapphire,omitempty"`
}
