// Code generated by "stringer -type=Exterior -output=exterior_string.go -linecomment"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BattleScarred-0]
	_ = x[FactoryNew-1]
	_ = x[FieldTested-2]
	_ = x[MinimalWear-3]
	_ = x[NotPainted-4]
	_ = x[WellWorn-5]
}

const _Exterior_name = "battle-scarredfactory newfield-testedminimal wearnot paintedwell-worn"

var _Exterior_index = [...]uint8{0, 14, 25, 37, 49, 60, 69}

func (i Exterior) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Exterior_index)-1 {
		return "Exterior(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Exterior_name[_Exterior_index[idx]:_Exterior_index[idx+1]]
}
