// Code generated by "stringer -type=Phase -output=phase_string.go -linecomment"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Doppler_Unknown-0]
	_ = x[Doppler_None-1]
	_ = x[Doppler_BlackPearl-2]
	_ = x[Doppler_Emerald-3]
	_ = x[Doppler_Phase1-4]
	_ = x[Doppler_Phase2-5]
	_ = x[Doppler_Phase3-6]
	_ = x[Doppler_Phase4-7]
	_ = x[Doppler_Ruby-8]
	_ = x[Doppler_Sapphire-9]
}

const _Phase_name = "Unknownblack-pearlemeraldphase-1phase-2phase-3phase-4rubysapphire"

var _Phase_index = [...]uint8{0, 7, 7, 18, 25, 32, 39, 46, 53, 57, 65}

func (i Phase) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Phase_index)-1 {
		return "Phase(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Phase_name[_Phase_index[idx]:_Phase_index[idx+1]]
}
