// Package listing provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package listing

import (
	"time"

	externalRef0 "github.com/MassimoMarsiglia/dmarket-bot/pkg/nats/emitter"
)

// ListingEvent defines model for ListingEvent.
type ListingEvent struct {
	// EventTimestamp When the event was emitted
	EventTimestamp time.Time         `json:"event_timestamp"`
	Item           externalRef0.Item `json:"item"`

	// Source Emitter source identifier
	Source string `json:"source"`
}
