// Code generated by "stringer -type=FloatPartValue -output=floatpartvalue_string.go -linecomment"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FloatPartValueEmpty-0]
	_ = x[FloatPartValueBS0-1]
	_ = x[FloatPartValueBS1-2]
	_ = x[FloatPartValueBS2-3]
	_ = x[FloatPartValueBS3-4]
	_ = x[FloatPartValueBS4-5]
	_ = x[FloatPartValueFN0-6]
	_ = x[FloatPartValueFN1-7]
	_ = x[FloatPartValueFN2-8]
	_ = x[FloatPartValueFN3-9]
	_ = x[FloatPartValueFN4-10]
	_ = x[FloatPartValueFN5-11]
	_ = x[FloatPartValueFN6-12]
	_ = x[FloatPartValueFT0-13]
	_ = x[FloatPartValueFT1-14]
	_ = x[FloatPartValueFT2-15]
	_ = x[FloatPartValueFT3-16]
	_ = x[FloatPartValueFT4-17]
	_ = x[FloatPartValueMW0-18]
	_ = x[FloatPartValueMW1-19]
	_ = x[FloatPartValueMW2-20]
	_ = x[FloatPartValueMW3-21]
	_ = x[FloatPartValueMW4-22]
	_ = x[FloatPartValueWW0-23]
	_ = x[FloatPartValueWW1-24]
	_ = x[FloatPartValueWW2-25]
	_ = x[FloatPartValueWW3-26]
	_ = x[FloatPartValueWW4-27]
}

const _FloatPartValue_name = "UnknownBS-0BS-1BS-2BS-3BS-4FN-0FN-1FN-2FN-3FN-4FN-5FN-6FT-0FT-1FT-2FT-3FT-4MW-0MW-1MW-2MW-3MW-4WW-0WW-1WW-2WW-3WW-4"

var _FloatPartValue_index = [...]uint8{0, 7, 11, 15, 19, 23, 27, 31, 35, 39, 43, 47, 51, 55, 59, 63, 67, 71, 75, 79, 83, 87, 91, 95, 99, 103, 107, 111, 115}

func (i FloatPartValue) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_FloatPartValue_index)-1 {
		return "FloatPartValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FloatPartValue_name[_FloatPartValue_index[idx]:_FloatPartValue_index[idx+1]]
}
