// Code generated by "stringer -type=MarketType -output=market_type_string.go -linecomment"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNKNOWN-0]
	_ = x[BUFF-1]
	_ = x[DMARKET-2]
}

const _MarketType_name = "unknownbuffdmark"

var _MarketType_index = [...]uint8{0, 7, 11, 16}

func (i MarketType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_MarketType_index)-1 {
		return "MarketType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MarketType_name[_MarketType_index[idx]:_MarketType_index[idx+1]]
}
