// Code generated by "stringer -type=SaleType -output=sale_type_string.go -linecomment"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Order-1]
	_ = x[Offer-2]
}

const _SaleType_name = "unknownordersale"

var _SaleType_index = [...]uint8{0, 7, 12, 16}

func (i SaleType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SaleType_index)-1 {
		return "SaleType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SaleType_name[_SaleType_index[idx]:_SaleType_index[idx+1]]
}
