// Package emitter provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package emitter

import (
	"time"
)

// Defines values for Exterior.
const (
	BattleScarred Exterior = "battle-scarred"
	FactoryNew    Exterior = "factory-new"
	FieldTested   Exterior = "field-tested"
	MinimalWear   Exterior = "minimal-wear"
	NotPainted    Exterior = "not-painted"
	WellWorn      Exterior = "well-worn"
)

// Defines values for FloatPartValue.
const (
	FloatPartValueBS0     FloatPartValue = "BS-0"
	FloatPartValueBS1     FloatPartValue = "BS-1"
	FloatPartValueBS2     FloatPartValue = "BS-2"
	FloatPartValueBS3     FloatPartValue = "BS-3"
	FloatPartValueBS4     FloatPartValue = "BS-4"
	FloatPartValueFN0     FloatPartValue = "FN-0"
	FloatPartValueFN1     FloatPartValue = "FN-1"
	FloatPartValueFN2     FloatPartValue = "FN-2"
	FloatPartValueFN3     FloatPartValue = "FN-3"
	FloatPartValueFN4     FloatPartValue = "FN-4"
	FloatPartValueFN5     FloatPartValue = "FN-5"
	FloatPartValueFN6     FloatPartValue = "FN-6"
	FloatPartValueFT0     FloatPartValue = "FT-0"
	FloatPartValueFT1     FloatPartValue = "FT-1"
	FloatPartValueFT2     FloatPartValue = "FT-2"
	FloatPartValueFT3     FloatPartValue = "FT-3"
	FloatPartValueFT4     FloatPartValue = "FT-4"
	FloatPartValueMW0     FloatPartValue = "MW-0"
	FloatPartValueMW1     FloatPartValue = "MW-1"
	FloatPartValueMW2     FloatPartValue = "MW-2"
	FloatPartValueMW3     FloatPartValue = "MW-3"
	FloatPartValueMW4     FloatPartValue = "MW-4"
	FloatPartValueUNKNOWN FloatPartValue = "UNKNOWN"
	FloatPartValueWW0     FloatPartValue = "WW-0"
	FloatPartValueWW1     FloatPartValue = "WW-1"
	FloatPartValueWW2     FloatPartValue = "WW-2"
	FloatPartValueWW3     FloatPartValue = "WW-3"
	FloatPartValueWW4     FloatPartValue = "WW-4"
)

// Defines values for Phase.
const (
	PhaseBlackPearl Phase = "black-pearl"
	PhaseEmerald    Phase = "emerald"
	PhaseNONE       Phase = "NONE"
	PhasePhase1     Phase = "phase-1"
	PhasePhase2     Phase = "phase-2"
	PhasePhase3     Phase = "phase-3"
	PhasePhase4     Phase = "phase-4"
	PhaseRuby       Phase = "ruby"
	PhaseSapphire   Phase = "sapphire"
	PhaseUNKNOWN    Phase = "UNKNOWN"
)

// Defines values for SaleType.
const (
	SaleTypeOrder   SaleType = "order"
	SaleTypeSale    SaleType = "sale"
	SaleTypeUnknown SaleType = "unknown"
)

// BuyOrder defines model for BuyOrder.
type BuyOrder struct {
	// Depth Order depth in the book
	Depth          int             `json:"depth"`
	FloatPartValue *FloatPartValue `json:"float_part_value,omitempty"`

	// Market Market source type
	Market string `json:"market"`

	// MarketHashName Item market hash name
	MarketHashName string `json:"market_hash_name"`

	// PaintSeed Optional paint seed
	PaintSeed *int `json:"paint_seed,omitempty"`

	// Phase Doppler phase variant.
	Phase *Phase `json:"phase,omitempty"`

	// Price Order price
	Price int `json:"price"`

	// SkinId Internal skin identifier
	SkinId    string    `json:"skin_id"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Exterior Item exterior condition.
type Exterior string

// FloatPartValue defines model for FloatPartValue.
type FloatPartValue string

// Item defines model for Item.
type Item struct {
	// Exterior Item exterior condition.
	Exterior       *Exterior       `json:"exterior,omitempty"`
	FloatPartValue *FloatPartValue `json:"float_part_value,omitempty"`

	// FloatValue Optional float value
	FloatValue *float32 `json:"float_value,omitempty"`

	// ImageUrl Item image URL
	ImageUrl string `json:"image_url"`
	ItemId   string `json:"item_id"`

	// Market Market source type
	Market string `json:"market"`

	// MarketHashName Item market hash name
	MarketHashName string `json:"market_hash_name"`
	OfferId        string `json:"offer_id"`

	// Owner Optional owner info
	Owner *ItemOwner `json:"owner,omitempty"`

	// PaintSeed Optional paint seed
	PaintSeed *int `json:"paint_seed,omitempty"`

	// Phase Doppler phase variant.
	Phase *Phase `json:"phase,omitempty"`

	// Price Item price
	Price int `json:"price"`

	// SkinId Internal skin identifier
	SkinId    string    `json:"skin_id"`
	Stickers  []Sticker `json:"stickers"`
	Timestamp time.Time `json:"timestamp"`
}

// ItemOwner Optional owner info
type ItemOwner struct {
	OwnerId  *string `json:"owner_id,omitempty"`
	WalletId *string `json:"wallet_id,omitempty"`
}

// Phase Doppler phase variant.
type Phase string

// Sale defines model for Sale.
type Sale struct {
	// Exterior Item exterior condition.
	Exterior       *Exterior       `json:"exterior,omitempty"`
	FloatPartValue *FloatPartValue `json:"float_part_value,omitempty"`

	// FloatValue Optional float value
	FloatValue *float32 `json:"float_value,omitempty"`

	// Market Market source type
	Market string `json:"market"`

	// MarketHashName Item market hash name
	MarketHashName string `json:"market_hash_name"`

	// PaintSeed Optional paint seed
	PaintSeed *int `json:"paint_seed,omitempty"`

	// Phase Doppler phase variant.
	Phase *Phase `json:"phase,omitempty"`

	// Price Sale price
	Price int `json:"price"`

	// SaleType Type of sale.
	SaleType SaleType `json:"sale_type"`

	// SkinId Internal skin identifier
	SkinId   string     `json:"skin_id"`
	Stickers *[]Sticker `json:"stickers,omitempty"`

	// StickersSupported Whether stickers are supported
	StickersSupported bool `json:"stickers_supported"`
}

// SaleType Type of sale.
type SaleType string

// Sticker defines model for Sticker.
type Sticker struct {
	// ImageUrl Sticker image url
	ImageUrl string `json:"image_url"`

	// Name Sticker name
	Name string `json:"name"`
}
