// Package CS2Models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package CS2Models

// Agent defines model for Agent.
type Agent struct {
	Description    string `json:"description"`
	Id             string `json:"id"`
	Image          string `json:"image"`
	MarketHashName string `json:"market_hash_name"`
	Name           string `json:"name"`
	Rarity         Rarity `json:"rarity"`
}

// Category defines model for Category.
type Category struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// Collection defines model for Collection.
type Collection struct {
	Id    string `json:"id"`
	Image string `json:"image"`
	Name  string `json:"name"`
}

// Crate defines model for Crate.
type Crate struct {
	FirstSaleDate  string `json:"first_sale_date"`
	Id             string `json:"id"`
	Image          string `json:"image"`
	MarketHashName string `json:"market_hash_name"`
	Name           string `json:"name"`
	Type           string `json:"type"`
}

// CrateRef defines model for CrateRef.
type CrateRef struct {
	Id    string `json:"id"`
	Image string `json:"image"`
	Name  string `json:"name"`
}

// Item defines model for Item.
type Item struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// Keychain defines model for Keychain.
type Keychain struct {
	Description    string `json:"description"`
	Id             string `json:"id"`
	Image          string `json:"image"`
	MarketHashName string `json:"market_hash_name"`
	Name           string `json:"name"`
	Rarity         Rarity `json:"rarity"`
}

// Pattern defines model for Pattern.
type Pattern struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// Rarity defines model for Rarity.
type Rarity struct {
	Color string `json:"color"`
	Id    string `json:"id"`
	Name  string `json:"name"`
}

// Skin defines model for Skin.
type Skin struct {
	Category    Category     `json:"category"`
	Collections []Collection `json:"collections"`
	Crates      *[]CrateRef  `json:"crates,omitempty"`
	Description string       `json:"description"`
	Id          string       `json:"id"`
	Image       *string      `json:"image,omitempty"`
	LegacyModel *bool        `json:"legacy_model,omitempty"`
	MaxFloat    float32      `json:"max_float"`
	MinFloat    float32      `json:"min_float"`
	Name        string       `json:"name"`
	PaintIndex  *string      `json:"paint_index,omitempty"`
	Pattern     Pattern      `json:"pattern"`
	Rarity      Rarity       `json:"rarity"`
	Souvenir    bool         `json:"souvenir"`
	Stattrak    bool         `json:"stattrak"`
	Team        *struct {
		Id   *string `json:"id,omitempty"`
		Name *string `json:"name,omitempty"`
	} `json:"team,omitempty"`
	Weapon Weapon `json:"weapon"`
	Wears  []Wear `json:"wears"`
}

// SkinNotGrouped defines model for SkinNotGrouped.
type SkinNotGrouped struct {
	Category       Category     `json:"category"`
	Collections    []Collection `json:"collections"`
	Crates         *[]CrateRef  `json:"crates,omitempty"`
	Description    string       `json:"description"`
	Id             string       `json:"id"`
	Image          *string      `json:"image,omitempty"`
	LegacyModel    *bool        `json:"legacy_model,omitempty"`
	MarketHashName string       `json:"market_hash_name"`
	MaxFloat       float32      `json:"max_float"`
	MinFloat       float32      `json:"min_float"`
	Name           string       `json:"name"`
	PaintIndex     *string      `json:"paint_index,omitempty"`
	Pattern        Pattern      `json:"pattern"`
	Rarity         Rarity       `json:"rarity"`
	SkinId         string       `json:"skin_id"`
	Souvenir       bool         `json:"souvenir"`
	Stattrak       bool         `json:"stattrak"`
	Style          struct {
		Id   *int    `json:"id,omitempty"`
		Name *string `json:"name,omitempty"`
		Url  *string `json:"url,omitempty"`
	} `json:"style"`
	Team *struct {
		Id   *string `json:"id,omitempty"`
		Name *string `json:"name,omitempty"`
	} `json:"team,omitempty"`
	Weapon Weapon `json:"weapon"`
	Wear   Wear   `json:"wear"`
	Wears  []Wear `json:"wears"`
}

// Sticker defines model for Sticker.
type Sticker struct {
	Description    string  `json:"description"`
	Id             string  `json:"id"`
	Image          string  `json:"image"`
	MarketHashName string  `json:"market_hash_name"`
	Name           string  `json:"name"`
	Rarity         *Rarity `json:"rarity,omitempty"`
}

// Weapon defines model for Weapon.
type Weapon struct {
	Id       string `json:"id"`
	Name     string `json:"name"`
	WeaponId int    `json:"weapon_id"`
}

// Wear defines model for Wear.
type Wear struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}
